name: archlinux.org news translate

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        cron_time=59
        date_now=`date +"%Y/%m/%d %H:%M:%S" -d "$cron_time minutes ago" -u`
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
        go get -v github.com/syui/xq
        url=${{ secrets.WEBHOOK_URL }}
        url_arch="https://www.archlinux.org/feeds/news/"
        url_archjp="https://www.archlinux.jp/feeds/news.xml"
        xml=index.xml
        xmljp=news.xml
        curl -sL $url_arch -o $xml
        curl -sLO $url_archjp
        date_xml=`date --date="$(xq p $xml)" +"%Y/%m/%d %H:%M:%S" -u`
        echo "ci-time : $date_now"
        echo "arch-time : $date_xml"
        date_now=`date -d "$date_now" +"%s"`
        date_xml=`date --date="$date_xml" +"%s"`
        echo "unix-time - arch:${date_xml}, ci:${date_now}"
        if [ "$date_xml" -gt "$date_now" ];then
            echo no news
            exit
        fi

        link=`xq $xml|jq -r ".[0].link"`
        link=${link%*/}
        # jp check
        linkjp=`xq $xmljp|jq -r ".[0].link"`
        linkjp=${linkjp%*/}
        if [ "${link##*/}" != "${linkjp##*/}" ];then
            echo updated jp;
            curl -sL -X POST --data-urlencode "payload={\"channel\": \"#general\" , \"username\": \"webhookbot\" , \"text\": \"${linkjp}\" , \"icon_emoji\": \":archjp:\"}" ${{ secrets.WEBHOOK_SLACK }}
            exit
        fi
        # translate
        title=`xq $xml|jq -r ".[0]|.title"`
        body=`xq $xml|jq -r ".[0]|.description"|tr -d '\n'|sed -e 's/<[^>]*>//g'`
        echo $title, $body
        title_ja=`curl -L -d "{\"txt\":\"$title\"}" $url`
        body_ja=`curl -L -d "{\"txt\":\"$body\"}" $url|sed 's/&#39;//g'`
        curl -sL -X POST --data-urlencode "payload={\"channel\": \"@syui\" , \"username\": \"webhookbot\" , \"text\": \"${link}\n${title}\n${body}\n${title_ja}\n${body_ja}\" , \"icon_emoji\": \":arch:\"}" ${{ secrets.WEBHOOK_SLACK }}
